services:
  web:
    build: .
    ports:
      - "4000:4000"  
    command: gunicorn --bind 0.0.0.0:4000 wsgi:app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    volumes:
      - .:/app
    networks:
      - app_network

networks:
  app_network: 
    driver: bridge  