version: '3'
services:
  web:
    build: .
    ports:
      - "4000:4000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:///servers.db
      - SECRET_KEY=your-secret-key-here
    command: gunicorn --bind 0.0.0.0:4000 --workers 4 --threads 2 wsgi:app
    volumes:
      - .:/app
      - sqlite_data:/app/instance

volumes:
  sqlite_data: 